-- ============================================================
-- Migration: journal_entries improvements
-- 1. Add followup_question column (was generated by AI but not synced)
-- 2. Enable RLS
-- ============================================================

ALTER TABLE journal_entries
    ADD COLUMN IF NOT EXISTS followup_question TEXT;

ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;

-- Users can only access their own entries
DROP POLICY IF EXISTS "journal_all" ON journal_entries;
CREATE POLICY "journal_all" ON journal_entries
    FOR ALL USING (auth.uid() = user_id);
